### ISSUE TITLE
StringResProvider vs Context or Resource

### ISSUE THREAD

**Issue by luongvo** [nhphong/nimble-surveys#15]
As your implementation [here](https://github.com/nhphong/nimble-surveys/blob/9395834871dfa985d640cb92b893d1893636c41d/app/src/main/java/com/nhphong/nimblesurveys/utils/StringResProvider.kt#L13), `StringResProvider` seems just a wrapper of Resource (or Context) and we have to define all string resources again like R.java class does. Could you let me know what is the good thing here?

**Comment by nhphong** [comment]
Hi @luongvo, the usage of `StringResProvider` is for the benefit of ViewModel (in a practical MVVM architecture). 
Very often, we encounter the situation when the ViewModel needs access to a `String` resource. To do that, we must have a `Context` object, but a ViewModel is not allowed to hold reference to the Activity.
Also, having a `StringResProvider` as one of the ViewModel's dependencies will help us completely remove Android-related stuff from the ViewModel implementation. It will help writing pure JUnit test (without Robolectric or Espresso)

Some references: https://stackoverflow.com/a/46667358

**Comment by luongvo** [comment]
Good understanding, thanks 👍

**Comment by nhphong** [comment]
Hi @luongvo, I think this [answer](https://stackoverflow.com/a/51451877) provides a much better reason on why we need `StringResProvider`.
Also, I would like to add one extra input: 
- If we choose to mock the `Context` object in the ViewModel test, we have to follow its prototype. And because it is Android stuff, so sometimes it's not possible to mock (for example, static method or final method...). 
- If we use `StringResProvider`, we are free to do any way we want.

**Comment by luongvo** [comment]
Anw, just my wondering 👌
